package commenter

import (
	"fmt"

	f "github.com/optiflowic/ghkit/internal/format"
	"github.com/optiflowic/ghkit/internal/source_url"
)

type Commenter struct {
}

func New() Commenter {
	return Commenter{}
}

func (c Commenter) PrependGeneratedComment(
	content []byte,
	format f.Format,
	referenceUrl string,
) []byte {
	var notice string
	switch format {
	case f.Yaml, f.PlaneText:
		notice = fmt.Sprintf(
			"### Generated by ghkit (%s)\n### %s\n\n",
			source_url.Repository,
			referenceUrl,
		)
	case f.Markdown:
		notice = fmt.Sprintf(
			"<!--\n  Generated by ghkit (%s)\n  %s\n-->\n\n",
			source_url.Repository,
			referenceUrl,
		)
	default:
		return content
	}
	return append([]byte(notice), content...)
}
